# Generated by Django 5.1.2 on 2024-10-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalskill',
            name='description',
        ),
    ]
